name: skybase
description: Code base for flutter using getx.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-alpha.1+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  get: ^4.7.2
  dio: ^5.9.0
  json_annotation: ^4.9.0
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^7.0.0
#  sliver_tools: ^0.2.12

  # File Manager
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  # flutter_image_compress: ^2.4.0
  path: ^1.9.1

  # Widget
  modal_bottom_sheet: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

  # Others
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  open_filex: ^4.7.0
  device_preview: ^1.3.1
  collection: ^1.19.1
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
#  change_app_package_name: ^1.4.0
#  rename: ^3.0.2
#  flutter_launcher_icons: ^0.14.1

flutter_gen:
  output: lib/config/themes
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#
# Usage :
# flutter pub run flutter_launcher_icons
#
#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true
#  remove_alpha_ios: true (Optional)
#  background_color_ios: "#ffffff" (Optional)